import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MainNav from '../components/nav/MainNav.js'
import React from "react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to next.js mastery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <MainNav/>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Coders Blog</h1>

        <p className={styles.description}>A blog for coders by the coders</p>

        <div className={styles.home_content}>
          <div className={styles.home_item}>
            <h3>How to learn javascript in 2022</h3>
            <p>Javascript is the language designed to run logic on the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          All right reserved
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      <script>var Alert = ReactBootstrap.Alert;</script>
    </div>
  );
}
